[theme]
base = "dark"
primaryColor = "#38bdf8"
backgroundColor = "#07090e"
secondaryBackgroundColor = "#0e1422"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
